version: '3.8'
services:
  nginx:
    image: nginx:1.19.0
    depends_on:
      - front
      - api
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  front:
    build:
        context: ./front
        dockerfile: Dockerfile
    tty: true
    command: npm run start
    volumes:
      - ./front:/app
      - node-modules:/app/node_modules
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /go/src/app
    tty: true
    command: run
    depends_on:
      - db
    volumes:
      - ./backend:/go/src/app
    env_file:
      - ./backend/.env
  db:
    image: postgres:12.3
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  db-data:
  node-modules:
