version: '3.8'
services:
  api:
    build: .
    tty: true
    command: fresh
    ports:
      - 8000:8000
    depends_on:
      - postgresql
    volumes:
      - ./:/app
    env_file:
      - ./.env
  postgresql:
    image: postgres:12.3
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  db-data:
