// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"go-project/domain/repository"
	"go-project/infrastructure/database"
	"go-project/interface/controller"
	"go-project/service"
)

// Injectors from wire.go:

// NewStatusController ...
func NewStatusController() *controller.StatusController {
	statusRepositoryImpl := repository.NewStatusRepositoryImpl()
	statusServiceImpl := service.NewStatusServiceImpl(statusRepositoryImpl)
	statusController := controller.NewStatusController(statusServiceImpl)
	return statusController
}

// NewUserController ...
func NewUserController(db database.Handler) *controller.UserController {
	userRepositoryImpl := repository.NewUserRepositoryImpl()
	userServiceImpl := service.NewUserServiceImpl(db, userRepositoryImpl)
	userController := controller.NewUserController(userServiceImpl)
	return userController
}
